### ISSUE TITLE
Probably don't need to ignore bower

### ISSUE THREAD

**Issue by gvn** [flukeout/curriculum-search-react#3]
For https://github.com/flukeout/curriculum-search-react/blob/gh-pages/webpack.config.js#L11 you can remove the `bower_components` exclusion I think. Guessing this was boilerplate? We don't use bower anymore, just npm.

**Comment by flukeout** [comment]
Yeah good call - also this is just the setup for my little dev env. I don't imagine when we move to the learning site that this structure will look the same.

**Comment by flukeout** [comment]
Removed
